In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#exporting dataset
ds = pd.read_csv("clean_ds.csv")
ds

Unnamed: 0  symboling  normalized-losses         make num-of-doors  \
0             0          3                  0  alfa-romero          two   
1             1          3                  0  alfa-romero          two   
2             2          1                  0  alfa-romero          two   
3             3          2                164         audi         four   
4             4          2                164         audi         four   
..          ...        ...                ...          ...          ...   
196         196         -1                 95        volvo         four   
197         197         -1                 95        volvo         four   
198         198         -1                 95        volvo         four   
199         199         -1                 95        volvo         four   
200         200         -1                 95        volvo         four   

      body-style drive-wheels engine-location  wheel-base    length  ...  \
0    convertible          rwd           front        88.6  0.811148  ...   
1    convertible          rwd           front        88.6  0.811148  ...   
2      hatchback          rwd           front        94.5  0.822681  ...   
3          sedan          fwd           front        99.8  0.848630  ...   
4          sedan          4wd           front        99.4  0.848630  ...   
..           ...          ...             ...         ...       ...  ...   
196        sedan          rwd           front       109.1  0.907256  ...   
197        sedan          rwd           front       109.1  0.907256  ...   
198        sedan          rwd           front       109.1  0.907256  ...   
199        sedan          rwd           front       109.1  0.907256  ...   
200        sedan          rwd           front       109.1  0.907256  ...   

     peak-rpm  city-mpg  highway-mpg    price city-L/100km  horsepower-binned  \
0      5000.0        21     8.703704  13495.0    11.190476                Low   
1      5000.0        21     8.703704  16500.0    11.190476                Low   
2      5000.0        19     9.038462  16500.0    12.368421             Medium   
3      5500.0        24     7.833333  13950.0     9.791667                Low   
4      5500.0        18    10.681818  17450.0    13.055556                Low   
..        ...       ...          ...      ...          ...                ...   
196    5400.0        23     8.392857  16845.0    10.217391                Low   
197    5300.0        19     9.400000  19045.0    12.368421             Medium   
198    5500.0        18    10.217391  21485.0    13.055556             Medium   
199    4800.0        26     8.703704  22470.0     9.038462                Low   
200    5400.0        19     9.400000  22625.0    12.368421                Low   

    fuel-type-diesel  fuel-type-gas  aspiration-std  aspiration-turbo  
0                  0              1               1                 0  
1                  0              1               1                 0  
2                  0              1               1                 0  
3                  0              1               1                 0  
4                  0              1               1                 0  
..               ...            ...             ...               ...  
196                0              1               1                 0  
197                0              1               0                 1  
198                0              1               1                 0  
199                1              0               0                 1  
200                0              1               0                 1  

[201 rows x 31 columns]

In [3]:
ds.dtypes

Unnamed: 0             int64
symboling              int64
normalized-losses      int64
make                  object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower             int64
peak-rpm             float64
city-mpg               int64
highway-mpg          float64
price                float64
city-L/100km         float64
horsepower-binned     object
fuel-type-diesel       int64
fuel-type-gas          int64
aspiration-std         int64
aspiration-turbo       int64
dtype: object

In [4]:
ds1 = ds.drop(['Unnamed: 0','make','num-of-doors','drive-wheels','engine-location','engine-type','num-of-cylinders','fuel-system','city-mpg','highway-mpg','city-L/100km','horsepower-binned'], axis=1)

In [5]:
ds1.dtypes


symboling              int64
normalized-losses      int64
body-style            object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-size            int64
bore                 float64
stroke               float64
compression-ratio    float64
horsepower             int64
peak-rpm             float64
price                float64
fuel-type-diesel       int64
fuel-type-gas          int64
aspiration-std         int64
aspiration-turbo       int64
dtype: object

In [6]:
org_data = ds1.reindex(columns=["body-style","symboling","normalized-losses","wheel-base", "length","width",
                         "height","curb-weight","engine-size","bore","stroke","compression-ratio","horsepower",
                         "peak-rpm","fuel-type-diesel","fuel-type-gas","aspiration-std","aspiration-turbo","price"])
org_data

body-style  symboling  normalized-losses  wheel-base    length  \
0    convertible          3                  0        88.6  0.811148   
1    convertible          3                  0        88.6  0.811148   
2      hatchback          1                  0        94.5  0.822681   
3          sedan          2                164        99.8  0.848630   
4          sedan          2                164        99.4  0.848630   
..           ...        ...                ...         ...       ...   
196        sedan         -1                 95       109.1  0.907256   
197        sedan         -1                 95       109.1  0.907256   
198        sedan         -1                 95       109.1  0.907256   
199        sedan         -1                 95       109.1  0.907256   
200        sedan         -1                 95       109.1  0.907256   

        width    height  curb-weight  engine-size  bore  stroke  \
0    0.890278  0.816054         2548          130  3.47    2.68   
1    0.890278  0.816054         2548          130  3.47    2.68   
2    0.909722  0.876254         2823          152  2.68    3.47   
3    0.919444  0.908027         2337          109  3.19    3.40   
4    0.922222  0.908027         2824          136  3.19    3.40   
..        ...       ...          ...          ...   ...     ...   
196  0.956944  0.928094         2952          141  3.78    3.15   
197  0.955556  0.928094         3049          141  3.78    3.15   
198  0.956944  0.928094         3012          173  3.58    2.87   
199  0.956944  0.928094         3217          145  3.01    3.40   
200  0.956944  0.928094         3062          141  3.78    3.15   

     compression-ratio  horsepower  peak-rpm  fuel-type-diesel  fuel-type-gas  \
0                  9.0         111    5000.0                 0              1   
1                  9.0         111    5000.0                 0              1   
2                  9.0         154    5000.0                 0              1   
3                 10.0         102    5500.0                 0              1   
4                  8.0         115    5500.0                 0              1   
..                 ...         ...       ...               ...            ...   
196                9.5         114    5400.0                 0              1   
197                8.7         160    5300.0                 0              1   
198                8.8         134    5500.0                 0              1   
199               23.0         106    4800.0                 1              0   
200                9.5         114    5400.0                 0              1   

     aspiration-std  aspiration-turbo    price  
0                 1                 0  13495.0  
1                 1                 0  16500.0  
2                 1                 0  16500.0  
3                 1                 0  13950.0  
4                 1                 0  17450.0  
..              ...               ...      ...  
196               1                 0  16845.0  
197               0                 1  19045.0  
198               1                 0  21485.0  
199               0                 1  22470.0  
200               0                 1  22625.0  

[201 rows x 19 columns]

In [7]:
X = org_data.iloc[:, :-1].values
Y = org_data.iloc[:, -1].values

In [8]:
print(X)

[['convertible' 3 0 ... 1 1 0]
 ['convertible' 3 0 ... 1 1 0]
 ['hatchback' 1 0 ... 1 1 0]
 ...
 ['sedan' -1 95 ... 1 1 0]
 ['sedan' -1 95 ... 0 0 1]
 ['sedan' -1 95 ... 1 0 1]]


In [9]:
print(Y)

[13495. 16500. 16500. 13950. 17450. 15250. 17710. 18920. 23875. 16430.
 16925. 20970. 21105. 24565. 30760. 41315. 36880.  5151.  6295.  6575.
  5572.  6377.  7957.  6229.  6692.  7609.  8558.  8921. 12964.  6479.
  6855.  5399.  6529.  7129.  7295.  7295.  7895.  9095.  8845. 10295.
 12945. 10345.  6785. 11048. 32250. 35550. 36000.  5195.  6095.  6795.
  6695.  7395. 10945. 11845. 13645. 15645.  8845.  8495. 10595. 10245.
 10795. 11245. 18280. 18344. 25552. 28248. 28176. 31600. 34184. 35056.
 40960. 45400. 16503.  5389.  6189.  6669.  7689.  9959.  8499. 12629.
 14869. 14489.  6989.  8189.  9279.  9279.  5499.  7099.  6649.  6849.
  7349.  7299.  7799.  7499.  7999.  8249.  8949.  9549. 13499. 14399.
 13499. 17199. 19699. 18399. 11900. 13200. 12440. 13860. 15580. 16900.
 16695. 17075. 16630. 17950. 18150.  5572.  7957.  6229.  6692.  7609.
  8921. 12764. 22018. 32528. 34028. 37028.  9295.  9895. 11850. 12170.
 15040. 15510. 18150. 18620.  5118.  7053.  7603.  7126.  7775.  9960.
  9233

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 0]
 [1.0 0.0 0.0 ... 1 1 0]
 [0.0 0.0 1.0 ... 1 1 0]
 ...
 [0.0 0.0 0.0 ... 1 1 0]
 [0.0 0.0 0.0 ... 0 0 1]
 [0.0 0.0 0.0 ... 1 0 1]]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [13]:
X_train

array([[0.0, 1.0, 0.0, ..., 0, 0, 1],
       [0.0, 0.0, 0.0, ..., 1, 0, 1],
       [0.0, 0.0, 0.0, ..., 0, 0, 1],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 1, 0],
       [0.0, 0.0, 1.0, ..., 1, 1, 0],
       [0.0, 0.0, 0.0, ..., 1, 1, 0]], dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
X_train

array([[-0.16012815,  4.67516233, -0.73379939, ..., -3.36269123,
        -2.12538029,  2.12538029],
       [-0.16012815, -0.21389632, -0.73379939, ...,  0.29738086,
        -2.12538029,  2.12538029],
       [-0.16012815, -0.21389632, -0.73379939, ..., -3.36269123,
        -2.12538029,  2.12538029],
       ...,
       [-0.16012815, -0.21389632,  1.36277029, ...,  0.29738086,
         0.47050403, -0.47050403],
       [-0.16012815, -0.21389632,  1.36277029, ...,  0.29738086,
         0.47050403, -0.47050403],
       [-0.16012815, -0.21389632, -0.73379939, ...,  0.29738086,
         0.47050403, -0.47050403]])

In [25]:
X_test

array([[ 2.22222454e-17,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         9.80000000e+01,  9.45000000e+01,  7.49159058e-01,
         8.83333333e-01,  8.69565217e-01,  1.87400000e+03,
         9.00000000e+01,  3.03000000e+00,  3.11000000e+00,
         9.60000000e+00,  7.00000000e+01,  5.40000000e+03,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         7.20502637e-17],
       [ 2.22222454e-17,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00, -1.00000000e+00,
         6.50000000e+01,  1.02400000e+02,  8.43825084e-01,
         9.23611111e-01,  9.18060201e-01,  2.48000000e+03,
         1.10000000e+02,  3.27000000e+00,  3.35000000e+00,
         2.25000000e+01,  7.30000000e+01,  4.50000000e+03,
         1.00000000e+00,  0.00000000e+00,  2.88201055e-16,
         1.00000000e+00],
       [ 2.22222454e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  4.42900510e-16,
    

In [26]:
Y_train

array([28176.,  8558., 17950., 17669., 18344., 23875.,  6669.,  6692.,
       10198., 45400., 34028.,  9995.,  9549.,  6918.,  6692.,  6855.,
        8238., 12945.,  8845., 15510.,  8949.,  8195.,  6575.,  7198.,
        7799., 13645.,  8449.,  7395.,  5499.,  9960.,  7349.,  7126.,
       17199.,  8013.,  6849., 16900., 30760.,  8921., 11259., 13295.,
       36000.,  7775., 16845., 15580., 18280., 16500., 10245.,  7603.,
       21485., 11048., 16925., 18420.,  5389., 19045.,  7775., 15998.,
        9295.,  7499., 16630.,  9258., 13415.,  6695., 13495.,  7999.,
       16695.,  8249., 25552., 11549., 10345., 35056.,  6795.,  6095.,
        9279., 24565.,  9298.,  6229.,  9980.,  7053.,  5572., 41315.,
        8499., 11900., 10945., 13499.,  7689., 13950.,  7957.,  9639.,
       22470., 17710., 34184.,  9279., 12764.,  7788.,  9988.,  7738.,
        7299., 22625., 20970.,  7609., 19699.,  7295.,  8495., 28248.,
       16500.,  8921.,  9538.,  6785., 13200., 18150., 11248.,  5151.,
      

In [27]:
Y_test

array([ 6295., 10698., 13860., 13499., 15750.,  8495., 15250.,  5348.,
       21105.,  6938., 11245., 37028.,  7995.,  7898., 14869., 18920.,
        7129., 15040.,  9095.,  6189.,  9495., 11694., 35550.,  8058.,
       10795., 32528.,  7975., 11595., 22018., 32250., 36880., 15645.,
        7898., 17075.,  7957., 12290., 12170., 17450.,  8189., 12440.,
        5118.])